### ISSUE TITLE
Monitoring: purging completions

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#13]

**Comment by kennsippell** [comment]
@mrjones-plip I have proposed [here](https://github.com/medic/cht-app-monitoring-data-ingest/pull/55) a more straight-forward approach to including purgelogs in app-monitoring.

**Comment by kennsippell** [comment]
Example output from app monitoring
![image](https://user-images.githubusercontent.com/9014751/221416670-2f4da8ef-7b4b-43c5-b38a-28afa28bb5ee.png)

**Comment by eljhkrr** [comment]
Feedback:

- Improve error formatting

- Human readable duration description

- Replace N/A with "Purging completed successfully"

**Comment by kennsippell** [comment]
Lets wait for https://github.com/medic/cht-core/issues/7355 which is currently scheduled? It will contain `purging frequency setting`

**Comment by mrjones-plip** [comment]
> Lets wait for https://github.com/medic/cht-core/issues/7355 which is currently scheduled?

7355 is not currently scheduled.  That said, it aligns well with both this repos efforts as well as Allies monitoring/alerting efforts.  Let me look into it!
