### ISSUE TITLE
App monitoring data ingest migration to public repository

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#34]
Public repository is: https://github.com/medic/cht-app-monitoring-data-ingest
Plan:
- [ ] switch to the new repository on November 10 after pending work has been merged.
- [x] create issue templates to warn against leaking PHI

**Comment by eljhkrr** [comment]
Thanks @mrjones-plip. I also had to convert the repository to private temporarily because it's not possible to transfer issues from a private repository to a public one.
Issue transfer is now complete, remaining bit is moving the code.

**Comment by mrjones-plip** [comment]
Wonderful - thanks for the follow up on this!
