### ISSUE TITLE
Improve handling of klipfolio data sources with refresh cycle set to 'never'

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#38]
Interesting case in MoH Mali supervisor app where a file-based datasource is set to never refresh and shows as a refresh failure:
![image](https://user-images.githubusercontent.com/4529018/197957388-997ed295-f8c6-4876-a82e-4fe7d92ed999.png)
![image](https://user-images.githubusercontent.com/4529018/197957556-328b9ff6-4128-46bc-b0de-09ceb6e08793.png)
This is a false positive and datasources like these should be filtered out

_Originally posted by @eljhkrr in https://github.com/medic/cht-app-monitoring-data-ingest/issues/22#issuecomment-1318526711_

**Comment by eljhkrr** [comment]
CMMB Kenya has datasources reported as failing 
![Screenshot from 2023-02-20 14-53-55](https://user-images.githubusercontent.com/4529018/220393957-b938c4c3-ef72-4056-bda2-fc0165bb93a0.png)
However, this is due to klipfolio suspending refresh due to the data being mostly static
![Screenshot from 2023-02-20 14-22-34](https://user-images.githubusercontent.com/4529018/220394236-20a274b1-e38b-4a44-8195-1b0d49db88d6.png)

**Comment by jdndiaye** [comment]
> ```
>     Interesting case in MoH Mali supervisor app where a file-based datasource is set to never refresh and shows as a refresh failure:
> ```
> 
> ![image](https://user-images.githubusercontent.com/4529018/197957388-997ed295-f8c6-4876-a82e-4fe7d92ed999.png) ![image](https://user-images.githubusercontent.com/4529018/197957556-328b9ff6-4128-46bc-b0de-09ceb6e08793.png) This is a false positive and datasources like these should be filtered out
> 
> _Originally posted by @eljhkrr in [#22 (comment)](https://github.com/medic/cht-app-monitoring-data-ingest/issues/22#issuecomment-1318526711)_

I've started looking at this ticket about the data source refresh problem. on supervisor_moh_mali, there are two data sources that don't refresh. geolocation ds has been removed from the db which is causing the refresh errors. I've recreated it and it's fine. As for Production - Months (English/French), there is static data that should come from an excel file. Normally, there should be no refresh. So I reconfigured
