### ISSUE TITLE
Replication metrics

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#42]
- [x] Replication success rate per day (probably a stacked bar graph of successes and failures)
- [x] Reasons why replications are failing - Probably a table
- [x] Total number of docs replicated
- [ ] Replication performance - How long is replication taking. Probably a [Box Plot](https://www.youtube.com/watch?v=OHKU5hfwY_k&ab_channel=PresetUser%27sCorner)
- [x] Move the "number of users above replication limit" from Vitals to Replication tab
- [x] Adding widget in superset

**Comment by kennsippell** [comment]
For the first: 

1. This is the query I'd [start with](https://github.com/medic/cht-app-monitoring-data-ingest/blob/main/postgres/functions/get_forms_by_completion.sql). 
2. I'd say we want to define success as `replication:medic:%:success` sum of count metric. And failure as `replication:medic:%:failure + replication:medic:%:denied`
3. In Superset can you use a stacked bar graph for this in a new tab called Replication?
4. You could actually have 3 series for the graph.  Success/Failure/Denied

**Comment by jdndiaye** [comment]
> For the first:
> 
> 1. This is the query I'd [start with](https://github.com/medic/cht-app-monitoring-data-ingest/blob/main/postgres/functions/get_forms_by_completion.sql).
> 2. I'd say we want to define success as `replication:medic:%:success` sum of count metric. And failure as `replication:medic:%:failure + replication:medic:%:denied`
> 3. In Superset can you use a stacked bar graph for this in a new tab called Replication?
> 4. You could actually have 3 series for the graph.  Success/Failure/Denied
> 
> You can create a pull request for this repository and we will deploy it in rdbms in the `dwh_impact` database.

OK Well noted! Thanks

**Comment by kennsippell** [comment]
This is an [exploratory analysis of replication data for three projects](https://docs.google.com/spreadsheets/d/1nUyRra9fqOK0jrKn4WCqTZMcdXoGJTrfaZ-xWWLHgk4/edit#gid=617106475). It includes some observations and design considerations for what we should build for this work.

**Comment by eljhkrr** [comment]
The new replication tab looks good!
![image](https://user-images.githubusercontent.com/4529018/222077708-014ce8ed-2c9e-4b15-b48b-2e78387c9cd9.png)
However, the "docs replicated as the delta per day" widget for PIH has an average of 6.6 million docs per day even on days with low activity e.g. 27th february there were 230 replication attempts (from replication health widget) vs doc delta of 6.62 million while on 20th february there were 8k+ replication attempt vs doc delta of 6.55 million. I would expect the two indicators to move proportionally in the same direction.

**Comment by jdndiaye** [comment]
@eljhkrr The values displayed on the "docs replicated as the delta per day" widget were not actually the delta. I just updated with the correct delta calculation.

**Comment by eljhkrr** [comment]
Feedback: 
Denied docs represent lost data and because this number is typically low, it gets swallowed by success/failure metrics. To make it more visible, the replication health graph can be split into two graphs with "Denied" and "Success/Failure":
![Screenshot from 2023-03-05 17-30-24](https://user-images.githubusercontent.com/4529018/223052969-b62e6cc4-bc0d-4740-9033-e860e58effdd.png)
![Screenshot from 2023-03-05 17-30-30](https://user-images.githubusercontent.com/4529018/223052976-49b07f64-3961-4c5b-ba97-29604d378a4b.png)

**Comment by eljhkrr** [comment]
Replication performance to be shown in 50th, 90th & 99th percentile

**Comment by kennsippell** [comment]
Great progress this sprint. I've split off https://github.com/medic/cht-app-monitoring-data-ingest/issues/74 with the remaining metric which is lower priority than what was tackled here.
