### ISSUE TITLE
New metric - core version of each project

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-app-monitoring-data-ingest#57]
Would be very useful to add the "CHT Core Version" onto the vitals tab for the project being viewed

**Comment by kennsippell** [comment]
Thanks @eljhkrr ! Can you kindly review the code change also?

**Comment by eljhkrr** [comment]
Scenario encountered for MoH Mali CHW with version string as '4.0.1-4.0.1.3593855120'
![image](https://user-images.githubusercontent.com/4529018/223751093-e324b060-09e2-44b8-9278-8cbe96d86ca9.png)

**Comment by kennsippell** [comment]
Superset `Big Number` control supports integers only... I think we need to upgrade Superset to latest to get the `markdown` widget to support arbitrary strings like this patch version
