### ISSUE TITLE
couch2pg backlog showing incorrect values for moh-mali-chw

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-app-monitoring-data-ingest#68]
This instance appears up-to-date but the dashboards are showing a significant backlog.
https://github.com/medic/config-moh-mali-chw/issues/602#issuecomment-1481366744

**Comment by derickl** [comment]
From Elijah on [slack](https://medic.slack.com/archives/C03CYKC7NUD/p1679585226132359?thread_ts=1679584475.836559&cid=C03CYKC7NUD) 

>We compare the couch2pg sequence with docs in couchdb

I think that would be incorrect. 1 doc in a db can be updated 100 times. So the sequence would be 100, but we only have 1 doc. With the cited approach, we’ll have a deviation of 99

**Comment by kennsippell** [comment]
Elijah is not correct. We are comparing a `seq` from couch2pg's `couchdb_progress` vs a `seq` from CouchDB via monitoring API.

**Comment by kennsippell** [comment]
![Image](https://user-images.githubusercontent.com/9014751/231544088-45b76068-e8ee-4525-8874-c810b00eb80c.png)
