### ISSUE TITLE
Devices tab not pulling data on insufficient disk space & chrome version

### ISSUE THREAD

**Issue by eljhkrr** [medic/cht-app-monitoring-data-ingest#84]
Observed for pih_malawi
![image (2)](https://user-images.githubusercontent.com/4529018/229632608-d4999222-2dde-462a-a874-660fc9d5161c.png)

**Comment by kennsippell** [comment]
Is it possible there really are no users with insufficient chrome version and with insufficient disk?  
If that is the case, what should this page look like? I would it expect what you are seeing above.

**Comment by derickl** [comment]
This is 'insufficient disk space' view is working as expected

```sql
SELECT
	partner_name,
	count(*),
	min(free_storage_mb),
	max(free_storage_mb)
FROM app_monitoring_users_with_insufficient_disk
GROUP BY 1;
```


|partner_name    |users_affected|min_available|max_available|
|----------------|--------------|-------------|-------------|
|supervisor_moh_mali|2             |129          |221          |
|vhw_burundi     |3             |110          |224          |
|brac-ug         |79            |56           |238          |
|cmmb-kenya-app  |2             |101          |190          |
|pih_malawi      |3             |70           |187          |
|sankhuwasabha_ne|1             |22           |22           |
|moh_zanzibar    |21            |7            |233          |
|zazic-scale-up  |1             |185          |185          |
|moh_mali_chw    |1             |250          |250          |

**Comment by derickl** [comment]
Closing as a noop.
