### ISSUE TITLE
New Metric - # of Successful Initial Replications

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-app-monitoring-data-ingest#86]
Realized we can measure the number of initial replications which are happening via telemetry documents. We can look at unique pairs of `deviceId` and `username` and when a new pair appears this indicates that a successful replication has completed.  

This would make a great widget for our replication dashboard and would be really helpful for a project experiencing [this incident](https://forum.communityhealthtoolkit.org/t/error-loading-tasks/2471/20) where users are clearing cache and re-syncing in the field.

**Comment by eljhkrr** [comment]
Already implemented in superset dashboard migration
