### ISSUE TITLE
Many instances in app-monitoring-data-ingest have NULL version

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-app-monitoring-data-ingest#9]
I believe that maybe these instances with `NULL` version are running CHT <3.9 which is before the [monitoring API](https://docs.communityhealthtoolkit.org/apps/reference/api/#monitoring) was introduced?

We can run this query to get all instances with and with out a version:

```sql
select
	mu.url  as url,
--	mu.partner_name as partner,
	max(md.created) as created,
	max(md.doc#>>'{version,app}') as version
from
	monitoring_urls mu 
left join monitoring_docs md on
	md.url_id = mu.id  
where 
	enabled = true
group by 
	url
order by 
	version 
```

These are the ones WITH a version, which is nice to see:

```
url                                                   |created                |version                   |
------------------------------------------------------+-----------------------+--------------------------+
https://msf-goma.app.medicmobile.org                  |2022-10-12 00:01:56.559|3.10.0                    |
https://adp-production.app.medicmobile.org            |2022-10-12 00:01:56.582|3.10.0                    |
https://safaridoctors-ke.app.medicmobile.org          |2022-10-12 00:01:56.577|3.10.0                    |
https://morang-ne.app.medicmobile.org                 |2022-10-12 00:01:56.574|3.10.0                    |
https://bhojpur-ne.app.medicmobile.org                |2022-10-12 00:01:56.631|3.10.2                    |
https://villagehealthworks-burundi.app.medicmobile.org|2022-10-12 00:01:56.625|3.10.3                    |
https://kfn-ilam.app.medicmobile.org                  |2022-10-12 00:01:56.580|3.10.3                    |
https://triggerise.app.medicmobile.org                |2022-10-12 00:01:56.602|3.10.3                    |
https://cmmb-kenya.app.medicmobile.org                |2022-10-12 00:01:56.554|3.10.3                    |
https://clone-brac-ug.dev.medicmobile.org             |2022-10-12 00:01:56.603|3.10.4                    |
https://brac-ug.app.medicmobile.org                   |2022-10-12 00:01:56.610|3.10.5                    |
https://sankhuwashabha-ne.app.medicmobile.org         |2022-10-12 00:01:56.645|3.11.0                    |
https://moh-ug-uncdf.app.medicmobile.org              |2022-10-12 00:01:56.586|3.11.0                    |
https://vhtapp.cphluganda.org                         |2022-10-12 00:01:56.561|3.11.0                    |
https://muso-cdi.app.medicmobile.org                  |2022-10-12 00:01:56.560|3.13.0                    |
https://hth-togo.app.medicmobile.org                  |2022-10-12 00:01:56.659|3.13.0                    |
https://muso-mali.app.medicmobile.org                 |2022-10-12 00:01:56.618|3.14.2                    |
https://pih-malawi.app.medicmobile.org                |2022-10-12 00:01:56.607|3.14.2                    |
https://bhaktapur-ne.app.medicmobile.org              |2022-10-12 00:01:56.563|3.14.2                    |
https://cloned-pih-malawi.dev.medicmobile.org         |2022-10-12 00:01:56.590|3.14.2                    |
https://chis.dohs.gov.np                              |2022-10-12 00:01:56.604|3.14.2                    |
https://safesimbaglung.app.medicmobile.org            |2022-10-12 00:01:56.593|3.14.2                    |
https://moh-zanzibar.app.medicmobile.org              |2022-10-12 00:01:56.557|3.15.0                    |
https://itech-zimbabwe.dev.medicmobile.org            |2022-10-12 00:01:56.583|3.15.0                    |
https://supervisor-moh-mali.app.medicmobile.org       |2022-10-12 00:01:56.622|3.15.0                    |
https://moh-niger-chw.app.medicmobile.org             |2022-10-12 00:01:56.597|3.15.0-FR-bulk-user-upload|
https://zazic-scale-up.app.medicmobile.org            |2022-10-12 00:01:56.628|3.16.0                    |
https://disc-mali.ml                                  |2022-10-12 00:01:56.596|3.16.0                    |
https://ohw-dhading.app.medicmobile.org               |2022-10-12 00:01:56.588|3.16.0                    |
https://dho-sunsari-ne.app.medicmobile.org            |2022-10-12 00:01:56.654|3.16.0                    |
https://itech-aurum.app.medicmobile.org               |2022-10-12 00:01:56.555|3.9.0                     |
https://malariaconsortium.app.medicmobile.org         |2022-10-12 00:01:56.599|3.9.0                     |
https://cht-cop-interop.dev.medicmobile.org           |2022-10-12 00:01:56.600|3.9.0                     |
```

And these are the instances with `NULL` for a version:

```
url                                                   |created                |version                   |
------------------------------------------------------+-----------------------+--------------------------+
https://dho-rasuwa-ne.app.medicmobile.org             |2022-10-12 00:01:56.649|                          |
https://kailali-ne.app.medicmobile.org                |2022-10-12 00:01:56.564|                          |
https://dpho-kanchanpur.app.medicmobile.org           |2022-10-12 00:01:56.615|                          |
https://dho-dadeldhura-ne.app.medicmobile.org         |2022-10-12 00:01:56.647|                          |
https://dho-bajura-ne.app.medicmobile.org             |2022-10-12 00:01:56.637|                          |
https://care-sindhuli.app.medicmobile.org             |2022-10-12 00:01:56.612|                          |
https://dhankuta-ne.app.medicmobile.org               |2022-10-12 00:01:56.633|                          |
https://dho-sindhupalchowk-ne.app.medicmobile.org     |2022-10-12 00:01:56.651|                          |
https://dpho-banke.app.medicmobile.org                |2022-10-12 00:01:56.613|                          |
https://panchthar-ne.app.medicmobile.org              |2022-10-12 00:01:56.639|                          |
https://alerte-covid19-ne.net                         |                       |                          |
https://syangja-ne.app.medicmobile.org                |2022-10-12 00:01:56.642|                          |
https://dpho-pyuthan-ne.app.medicmobile.org           |2022-10-12 00:01:56.656|                          |
https://cht.app.medicmobile.org                       |                       |                          |
https://srhgorkha.app.medicmobile.org                 |2022-10-12 00:01:56.620|                          |
https://dho-baitadi.app.medicmobile.org               |2022-10-12 00:01:56.635|                          |
```

**Comment by eljhkrr** [comment]
Most instances now have version information after upgrading
|url                                                   |created                   |version                   |
|------------------------------------------------------|--------------------------|--------------------------|
|https://adp-production.app.medicmobile.org            |2023-03-12 00:01:47.821241|3.10.0                    |
|https://msf-goma.app.medicmobile.org                  |2023-03-12 00:01:47.798052|3.10.0                    |
|https://villagehealthworks-burundi.app.medicmobile.org|2023-03-12 00:01:47.880854|3.10.3                    |
|https://cmmb-kenya.app.medicmobile.org                |2023-03-12 00:01:47.792781|3.10.3                    |
|https://triggerise.app.medicmobile.org                |2023-03-12 00:01:47.84134 |3.10.3                    |
|https://clone-brac-ug.dev.medicmobile.org             |2023-03-12 00:01:47.842642|3.10.4                    |
|https://brac-ug.app.medicmobile.org                   |2023-03-12 00:01:47.857376|3.10.5                    |
|https://moh-ug-uncdf.app.medicmobile.org              |2023-03-12 00:01:47.825338|3.11.0                    |
|https://vhtapp.cphluganda.org                         |2023-03-12 00:01:47.851017|3.11.0                    |
|https://hth-togo.app.medicmobile.org                  |2023-03-12 00:01:47.935505|3.13.0                    |
|https://cloned-pih-malawi.dev.medicmobile.org         |2023-03-12 00:01:47.831727|3.14.2                    |
|https://chis.dohs.gov.np                              |2023-03-12 00:01:47.847097|3.14.2                    |
|https://pih-malawi.app.medicmobile.org                |2023-03-12 00:01:47.853523|3.14.2                    |
|https://bhaktapur-ne.app.medicmobile.org              |2023-03-12 00:01:47.801908|3.14.2                    |
|https://moh-zanzibar.app.medicmobile.org              |2023-03-12 00:01:47.848441|3.15.0                    |
|https://muso-cdi.app.medicmobile.org                  |2023-03-12 00:01:47.861777|3.15.0                    |
|https://muso-mali.app.medicmobile.org                 |2023-03-12 00:01:47.871654|3.15.0                    |
|https://supervisor-moh-mali.app.medicmobile.org       |2023-03-12 00:01:47.87716 |3.15.0                    |
|https://itech-zimbabwe.dev.medicmobile.org            |2023-03-12 00:01:47.822412|3.15.0                    |
|https://moh-niger-chw.app.medicmobile.org             |2023-03-12 00:01:47.837097|3.15.0-FR-bulk-user-upload|
|https://zazic-scale-up.app.medicmobile.org            |2023-03-12 00:01:47.845818|3.16.0                    |
|https://echis.health.go.ke                            |2023-03-12 00:01:47.849766|3.17.0                    |
|https://dho-rasuwa-ne.app.medicmobile.org             |2023-03-12 00:01:47.91815 |3.17.1                    |
|https://dhankuta-ne.app.medicmobile.org               |2023-03-12 00:01:47.8895  |3.17.1                    |
|https://sankhuwashabha-ne.app.medicmobile.org         |2023-03-12 00:01:47.909341|3.17.1                    |
|https://safesimbaglung.app.medicmobile.org            |2023-03-12 00:01:47.834447|3.17.1                    |
|https://care-sindhuli.app.medicmobile.org             |2023-03-12 00:01:47.860573|3.17.1                    |
|https://panchthar-ne.app.medicmobile.org              |2023-03-12 00:01:47.901226|3.17.1                    |
|https://dpho-banke.app.medicmobile.org                |2023-03-12 00:01:47.864537|3.17.1                    |
|https://ohw-dhading.app.medicmobile.org               |2023-03-12 00:01:47.82973 |3.17.1                    |
|https://dpho-kanchanpur.app.medicmobile.org           |2023-03-12 00:01:47.868256|3.17.1                    |
|https://kailali-ne.app.medicmobile.org                |2023-03-12 00:01:47.804493|3.17.1                    |
|https://dho-dadeldhura-ne.app.medicmobile.org         |2023-03-12 00:01:47.913955|3.17.1                    |
|https://kfn-ilam.app.medicmobile.org                  |2023-03-12 00:01:47.819122|3.17.1                    |
|https://dho-baitadi.app.medicmobile.org               |2023-03-12 00:01:47.893824|3.17.1                    |
|https://srhgorkha.app.medicmobile.org                 |2023-03-12 00:01:47.874508|3.17.1                    |
|https://dho-sunsari-ne.app.medicmobile.org            |2023-03-12 00:01:47.926277|3.17.1                    |
|https://morang-ne.app.medicmobile.org                 |2023-03-12 00:01:47.814209|3.17.1                    |
|https://dho-bajura-ne.app.medicmobile.org             |2023-03-12 00:01:47.897451|3.17.1                    |
|https://dho-sindhupalchowk-ne.app.medicmobile.org     |2023-03-12 00:01:47.922688|3.17.1                    |
|https://syangja-ne.app.medicmobile.org                |2023-03-12 00:01:47.905132|3.17.1                    |
|https://dpho-pyuthan-ne.app.medicmobile.org           |2023-03-12 00:01:47.930583|3.17.1                    |
|https://bhojpur-ne.app.medicmobile.org                |2023-03-12 00:01:47.88436 |3.17.1                    |
|https://itech-aurum.app.medicmobile.org               |2023-03-12 00:01:47.794264|3.9.0                     |
|https://cht-cop-interop.dev.medicmobile.org           |2023-03-12 00:01:47.839759|3.9.0                     |
|https://malariaconsortium.app.medicmobile.org         |2023-03-12 00:01:47.838408|3.9.0                     |
|https://disc-mali.ml                                  |2023-03-12 00:01:47.816344|4.1.0-4.1.0.3674603789    |
|https://cht.app.medicmobile.org                       |                          |                          |
|https://alerte-covid19-ne.net                         |2023-02-21 00:01:40.341822|                          |
